$(function(){
	//导航切换
	$('.moreNav').on('click',function(){	
		if($(this).attr('isOpen')=='false'){
			$(this).attr('isOpen',true);
			$('.navBox').stop().slideDown();
			$(this).addClass('mn45');
		}else{
			$(this).attr('isOpen',false);
			$('.navBox').stop().slideUp();
			$(this).removeClass('mn45');
		}
	});
});
